jewelryshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
]

# To display images
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from store.forms import LoginForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'store'


urlpatterns = [
    path('', views.home, name="home"),
    # URL for Cart and Checkout
    path('add-to-cart/', views.add_to_cart, name="add-to-cart"),
    path('add-coupon/', views.AddCoupon.as_view(), name="add-coupon"),
    path('remove-cart/<int:cart_id>/', views.remove_cart, name="remove-cart"),
    path('plus-cart/<int:cart_id>/', views.plus_cart, name="plus-cart"),
    path('minus-cart/<int:cart_id>/', views.minus_cart, name="minus-cart"),
    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('orders/', views.orders, name="orders"),
    path("search/", views.search_view, name="search"),
    path("filter-products/", views.filter_product, name="filter-product"),
    path('products/', views.products, name="all-products"),
    path('brands/', views.all_brands, name="all-brands"),
    path('brand/<slug:slug>/', views.brand_products, name="brand-products"),
    path('product/test/', views.test, name="test"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),

    #URL for Products
    path('product/<slug:slug>/', views.detail, name="product-detail"),
    path('categories/', views.all_categories, name="all-categories"),
    path('<slug:slug>/', views.category_products, name="category-products"),


    path('shop/', views.shop, name="shop"),

    # URL for Authentication
    path('accounts/register/', views.RegistrationView.as_view(), name="register"),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='account/login.html', authentication_form=LoginForm), name="login"),
    path('accounts/profile/', views.profile, name="profile"),
    path('accounts/add-address/', views.AddressView.as_view(), name="add-address"),
    path('accounts/remove-address/<int:id>/', views.remove_address, name="remove-address"),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='store:login'), name="logout"),

    path('accounts/password-change/', auth_views.PasswordChangeView.as_view(template_name='account/password_change.html', form_class=PasswordChangeForm, success_url='/accounts/password-change-done/'), name="password-change"),
    path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'), name="password-change-done"),

    path('accounts/password-reset/', auth_views.PasswordResetView.as_view(template_name='account/password_reset.html', form_class=PasswordResetForm, success_url='/accounts/password-reset/done/'), name="password-reset"), # Passing Success URL to Override default URL, also created password_reset_email.html due to error from our app_name in URL
    path('accounts/password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'), name="password_reset_done"),
    path('accounts/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html', form_class=SetPasswordForm, success_url='/accounts/password-reset-complete/'), name="password_reset_confirm"), # Passing Success URL to Override default URL
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), name="password_reset_complete"),


    
]
# def cart(request):
#     user = request.user
#     cart_products = Cart.objects.filter(user=user)

#     # Display Total on Cart Page
#     amount = decimal.Decimal(0)
#     shipping_amount = decimal.Decimal(40)
#     # using list comprehension to calculate total amount based on quantity and shipping
#     cp = [p for p in Cart.objects.all() if p.user==user]
#     if cp:
#         for p in cp:
#             temp_amount = (p.quantity * p.product.price)
#             amount += temp_amount

#     # Customer Addresses
#     addresses = Address.objects.filter(user=user)

#     context = {
#         'cart_products': cart_products,
#         'amount': amount,
#         'shipping_amount': shipping_amount,
#         'total_amount': amount + shipping_amount,
#         'addresses': addresses,
#     }
#     return render(request, 'store/cart.html', context)

templates/footer1.html
<!-- Start of Footer -->
{% load static %}

<footer class="footer">
    {% comment %} <div class="footer-newsletter bg-primary pt-6 pb-6">
        <div class="container">
            <div class="row justify-content-center align-items-center">
                <div class="col-xl-5 col-lg-6">
                    <div class="icon-box icon-box-side text-white">
                        <div class="icon-box-icon d-inline-flex">
                            <i class="w-icon-envelop3"></i>
                        </div>
                        <div class="icon-box-content">
                            <h4 class="icon-box-title text-white text-uppercase mb-0">Subscribe To  Our Newsletter</h4>
                            <p class="text-white">Get all the latest information on Events, Sales and Offers.</p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-7 col-lg-6 col-md-9 mt-4 mt-lg-0 ">
                    <form action="#" method="get" class="input-wrapper input-wrapper-inline input-wrapper-rounded">
                        <input type="email" class="form-control mr-2 bg-white" name="email" id="email"
                            placeholder="Your E-mail Address" />
                    <button class="btn btn-dark btn-rounded" type="submit">Subscribe<i
                            class="w-icon-long-arrow-right"></i></button>
                    </form>
                </div>
            </div>
        </div>
    </div> {% endcomment %}
    <div class="container">
        <div class="footer-top">
            <div class="row">
                <div class="col-lg-4 col-sm-6">
                    <div class="widget widget-about">
                        <a href="demo1.html" class="logo-footer">
                            <img src="{% static 'asset/images/logo_footer.png' %}" alt="logo-footer" width="144"
                                height="45" />
                        </a>
                        <div class="widget-body">
                            <p class="widget-about-title">Got Question? Call us 24/7</p>
                            <a href="tel:18005707777" class="widget-about-call">1-800-570-7777</a>
                            <p class="widget-about-desc">Register now to get updates on pronot get up icons
                                & coupons ster now toon.
                            </p>

                            <div class="social-icons social-icons-colored">
                                <a href="https://www.linkedin.com/company/zentanee/" class="social-icon social-youtube fab fa-linkedin-in"></a>
                              <a href="https://www.instagram.com/zentanee/" class="social-icon social-instagram w-icon-instagram"></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="widget">
                        <h3 class="widget-title">Company</h3>
                        <ul class="widget-body">
                            <li><a href="{% url 'store:about' %}">About Us</a></li>
                            <li><a href="https://instagram.com/zentanee">Team Member</a></li>
                            <li><a href="{% url 'store:contact' %}">Contact Us</a></li>
                            <li><a href="https://instagram.com/zentanee">Affilate</a></li>
                            <li><a href="{% url 'store:orders' %}">Order History</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="widget">
                        <h4 class="widget-title">My Account</h4>
                        <ul class="widget-body">
                            <li><a href="{% url 'store:cart' %}">View Cart</a></li>
                            <li><a href="{% url 'store:login' %}">Sign In</a></li>
                            <li><a href="https://instagram.com/zentanee">Help</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="widget">
                        <h4 class="widget-title">Customer Service</h4>
                        <ul class="widget-body">
                            <li><a href="https://instagram.com/zentanee">Payment Methods</a></li>
                            <li><a href="https://instagram.com/zentanee">Money-back guarantee!</a></li>
                            <li><a href="https://instagram.com/zentanee">Product Returns</a></li>
                            <li><a href="https://instagram.com/zentanee">Support Center</a></li>
                            <li><a href="https://instagram.com/zentanee">Shipping</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            <div class="footer-left">
                <p class="copyright">Copyright © 2025 Zentanee. All Rights Reserved.</p>
            </div>
            <div class="footer-right">
                <span>Website by >>></span><a href="https://instagram.com/mosesyaicob" class="social-icon social-instagram w-icon-instagram"></a>

            </div>
        </div>
    </div>
</footer>
<!-- End of Footer -->

templates/navbar.html
{% load static %}

<!-- navbar-->
      <header class="header bg-white">
        <div class="container px-0 px-lg-3">
          <nav class="navbar navbar-expand-lg navbar-light py-3 px-lg-0"><a class="navbar-brand" href="{% url 'store:home' %}"><span class="font-weight-bold text-uppercase text-dark">Zentanee</span></a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <!-- Link--><a class="nav-link active" href="{% url 'store:home' %}">Home</a>
                </li>
                <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="pagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
                  <div class="dropdown-menu mt-3" aria-labelledby="pagesDropdown">
                    {% if categories_menu %}
                      {% for cat_menu in categories_menu %}
                        <a class="dropdown-item border-0 transition-link" href="{% url 'store:category-products' cat_menu.slug %}">{{cat_menu.title}}</a>
                      {% endfor %}
                    {% endif %}
                    <hr>
                    <a class="dropdown-item border-0 transition-link" href="{% url 'store:all-categories' %}">All Categories</a>
                  </div>
                </li>
                <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="pagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Brands</a>
                  <div class="dropdown-menu mt-3" aria-labelledby="pagesDropdown">
                    {% if brands_menu %}
                      {% for bra_menu in brands_menu %}
                        <a class="dropdown-item border-0 transition-link" href="{% url 'store:brand-products' bra_menu.slug %}">{{bra_menu.title}}</a>
                      {% endfor %}
                    {% endif %}
                    <hr>
                    <a class="dropdown-item border-0 transition-link" href="{% url 'store:all-brands' %}">All Brands</a>
                  </div>
                </li>
                {% comment %} <li class="nav-item">
                  <!-- Link--><a class="nav-link" href="{% url 'store:home' %}">Contact</a>
                </li><br> {% endcomment %}
              <form action="{% url 'store:search' %}" method="GET" >
                  <input type="text" placeholder="Search for items..." name="q" />
                  <button style="background: none; border: none;" type="submit"><i class="fi-rs-search"></i></button>
              </form>
              </ul>
              <ul class="navbar-nav ml-auto"> 
                {% if request.user.is_authenticated %}           
                  <li class="nav-item"><a class="nav-link" href="{% url 'store:cart' %}"> <i class="fas fa-dolly-flatbed mr-1 text-gray"></i>Cart<small class="text-gray"> [{{cart_items.count}}]</small></a></li>
                  {% comment %} <li class="nav-item"><a class="nav-link" href="#"> <i class="far fa-heart mr-1"></i><small class="text-gray"> (0)</small></a></li> {% endcomment %}
                  {% comment %} <li class="nav-item"><a class="nav-link" href="#"> <i class="fas fa-user-alt mr-1 text-gray"></i>My Account</a></li> {% endcomment %}

                  <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="pagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-alt mr-1 text-gray"></i>My Account</a></a>
                  
                  <div class="dropdown-menu mt-3" aria-labelledby="pagesDropdown">
                    
                      <a class="dropdown-item border-0 transition-link" href="{% url 'store:profile' %}">Profile</a>
                      <a class="dropdown-item border-0 transition-link" href="{% url 'store:cart' %}">Cart</a>
                      <a class="dropdown-item border-0 transition-link" href="{% url 'store:orders' %}">Orders</a>
                      <a class="dropdown-item border-0 transition-link" href="{% url 'store:password-change' %}">Change Password</a>

                    <hr>
                    <a class="dropdown-item border-0 transition-link" href="{% url 'store:logout' %}">Log Out</a>
                    
                </li>
                {% else %}
                  <li class="nav-item"><a class="nav-link" href="{% url 'store:login' %}">Login</a></li>
                  <li class="nav-item"><a class="nav-link" href="{% url 'store:register' %}">Create Account</a></li>
                {% endif %}   
              </ul>
            </div>
          </nav>
        </div>
      </header>

templates/navbar1.html
{% load static %}

<!-- navbar-->
      <!-- Start of Header -->
      <header class="header">
        <div class="header-top">
            <div class="container">
                <div class="header-left">
                    <p class="welcome-msg">Welcome to Wolmart Store message or remove it!</p>
                </div>
                <div class="header-right">
                    {% comment %} <div class="dropdown">
                        <a href="#currency">USD</a>
                        <div class="dropdown-box">
                            <a href="#USD">USD</a>
                            <a href="#EUR">EUR</a>
                        </div>
                    </div> {% endcomment %}
                    <!-- End of DropDown Menu -->

                    {% comment %} <div class="dropdown">
                        <a href="#language"><img src="{% static 'asset/images/flags/eng.png' %}" alt="ENG Flag" width="14"
                                height="8" class="dropdown-image" /> ENG</a>
                        <div class="dropdown-box">
                            <a href="#ENG">
                                <img src="{% static 'asset/images/flags/eng.png' %}" alt="ENG Flag" width="14" height="8"
                                    class="dropdown-image" />
                                ENG
                            </a>
                            <a href="#FRA">
                                <img src="{% static 'asset/images/flags/fra.png' %}" alt="FRA Flag" width="14" height="8"
                                    class="dropdown-image" />
                                FRA
                            </a>
                        </div>
                    </div> {% endcomment %}
                    <!-- End of Dropdown Menu -->
                    <span class="divider d-lg-show"></span>
                    {% comment %} <a href="blog.html" class="d-lg-show">Blog</a> {% endcomment %}
                    <a href="{% url 'store:contact' %}" class="d-lg-show">Contact Us</a>
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'store:profile' %}" class="d-lg-show">My Account</a>
                    {% else %}
                    <a href="{% url 'store:login' %}" class="d-lg-show login sign-in"><i
                            class="w-icon-account"></i>Login</a>
                    <span class="delimiter d-lg-show">/</span>
                    <a href="{% url 'store:register' %}" class="ml-0 d-lg-show login register">Register</a>
                    {% endif %} 
                </div>
            </div>
        </div>
        <!-- End of Header Top -->

        <div class="header-middle">
            <div class="container">
                <div class="header-left mr-md-4">
                    <a href="#" class="mobile-menu-toggle  w-icon-hamburger" aria-label="menu-toggle">
                    </a>
                    <a href="{% url 'store:home' %}" class="logo ml-lg-0">
                        <img src="{% static 'asset/images/logo.png' %}" alt="logo" width="144" height="45" />
                    </a>
                    <form action="{% url 'store:search' %}" method="GET" class="header-search hs-expanded hs-round d-none d-md-flex input-wrapper">
                        <div class="select-box">
                            <select id="category" name="category">
                                <option value="">All Categories</option>
                                <option value="4">Fashion</option>
                                <option value="5">Furniture</option>
                                <option value="6">Shoes</option>
                                <option value="7">Sports</option>
                                <option value="8">Games</option>
                                <option value="9">Computers</option>
                                <option value="10">Electronics</option>
                                <option value="11">Kitchen</option>
                                <option value="12">Clothing</option>
                            </select>
                        </div>
                        <input type="text" class="form-control" name="q" id="search"
                            placeholder="Search in..." required />
                        <button class="btn btn-search" type="submit"><i class="w-icon-search"></i>
                        </button>
                    </form>
                </div>
                <div class="header-right ml-4">
                    <div class="header-call d-xs-show d-lg-flex align-items-center">
                        <a href="tel:#" class="w-icon-call"></a>
                        <div class="call-info d-lg-show">
                            <h4 class="chat font-weight-normal font-size-md text-normal ls-normal text-light mb-0">
                                <a href="mailto:#" class="text-capitalize">Live Chat</a> or :</h4>
                            <a href="tel:#" class="phone-number font-weight-bolder ls-50">0(800)123-456</a>
                        </div>
                    </div>
                    
                    <div class="dropdown cart-dropdown cart-offcanvas mr-0 mr-lg-2">
                        <div class="cart-overlay"></div>
                        <a href="{% url 'store:cart' %}" class="cart-toggle label-down link">
                            <i class="w-icon-cart">
                                <span class="cart-count">{{cart_items.count}}</span>
                            </i>
                            <span class="cart-label">Cart</span>
                        </a>
                        
                    </div>
                </div>
            </div>
        </div>
        <!-- End of Header Middle -->

        <div class="header-bottom sticky-content fix-top sticky-header">
            <div class="container">
                <div class="inner-wrap">
                    <div class="header-left">
                        <div class="dropdown category-dropdown has-border" data-visible="true">
                            <a href="#" class="category-toggle" role="button" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="true" data-display="static"
                                title="Browse Categories">
                                <i class="w-icon-category"></i>
                                <span>Browse Categories</span>
                            </a>

                            <div class="dropdown-box">
                                <ul class="menu vertical-menu category-menu">
                                    {% if categories_menu %}
                                    {% for cat_menu in categories_menu %}
                                    <li>
                                        <a href="{% url 'store:category-products' cat_menu.slug %}">
                                            </i><b>{{cat_menu.title}}</b>
                                        </a>
                                    </li>
                                    
                                    {% endfor %}
                                    {% endif %}
                                    <li>
                                        <a href="{% url 'store:all-categories' %}"
                                            class="font-weight-bold text-primary text-uppercase ls-25">
                                            View All Categories<i class="w-icon-angle-right"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <nav class="main-nav">
                            <ul class="menu active-underline">
                                <li>
                                    <a href="{% url 'store:home' %}">Home</a>
                                </li>
                                <li>
                                    <a href="{% url 'store:all-categories' %}">All categories</a>
                                </li>
                                <li>
                                    <a href="{% url 'store:all-brands' %}">Brands</a>
                                </li>
                                <li>
                                    <a href="{% url 'store:about' %}">About us</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                    <div class="header-right">
                        <a href="#"><i class="w-icon-sale"></i>Daily Deals</a>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- End of Header -->

templates/scripts.html
{% load static %}

<!-- JavaScript files-->
      {% comment %} <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'vendor/lightbox2/js/lightbox.min.js' %}"></script>
      <script src="{% static 'vendor/nouislider/nouislider.min.js' %}"></script>
      <script src="{% static 'vendor/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
      <script src="{% static 'vendor/owl.carousel2/owl.carousel.min.js' %}"></script>
      <script src="{% static 'vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.min.js' %}"></script>
      <script src="{% static 'js/front.js' %}"></script>

      <script>
        var range = document.getElementById('range');
        noUiSlider.create(range, {
            range: {
                'min': 0,
                'max': 2000
            },
            step: 5,
            start: [100, 1000],
            margin: 300,
            connect: true,
            direction: 'ltr',
            orientation: 'horizontal',
            behaviour: 'tap-drag',
            tooltips: true,
            format: {
              to: function ( value ) {
                return '$' + value;
              },
              from: function ( value ) {
                return value.replace('', '');
              }
            }
        });
        
      </script>

      
      <script>
        // ------------------------------------------------------- //
        //   Inject SVG Sprite - 
        //   see more here 
        //   https://css-tricks.com/ajaxing-svg-sprite/
        // ------------------------------------------------------ //
        function injectSvgSprite(path) {
        
            var ajax = new XMLHttpRequest();
            ajax.open("GET", path, true);
            ajax.send();
            ajax.onload = function(e) {
            var div = document.createElement("div");
            div.className = 'd-none';
            div.innerHTML = ajax.responseText;
            document.body.insertBefore(div, document.body.childNodes[0]);
            }
        }
        // this is set to BootstrapTemple website as you cannot 
        // inject local SVG sprite (using only 'icons/orion-svg-sprite.svg' path)
        // while using file:// protocol
        // pls don't forget to change to your domain :)
        injectSvgSprite('https://bootstraptemple.com/files/icons/orion-svg-sprite.svg'); 
        
      </script>
      <script>
        $(document).ready(function (){
          $(".filter-checkbox, #price-filter-btn").on("click", function(){
              console.log("A check box has been clicked");
      
              let filter_object = {}
      
              let min_price = $("#max_price").attr("min")
              let max_price = $("#max_price").val()
      
              filter_object.min_price = min_price;
              filter_object.max_price = max_price;
      
              $(".filter-checkbox").each(function(){
                  let filter_value = $(this).val()
                  let filter_key = $(this).data("filter")
      
                  //console.log("Filter value is:", filter_value);
                  //console.log("Filter key is:", filter_key);
      
                  filter_object[filter_key] = Array.from(document.querySelectorAll('input[data-filter=' + filter_key + ']:checked')).map(function(element){
                      return element.value
                  })
              })
              console.log("Filter object is: ", filter_object);
              $.ajax({
                  url: '/filter-products',
                  data: filter_object,
                  dataType: 'json',
                  beforeSend: function(){
                      console.log("Trying to filter product...");
                  },
                  success: function(response){
                      console.log(response);
                      console.log("Data filtered successfully...");
                      $("#filtered-product").html(response.data)
                  }
              })
          })
      
          $("#max_price").on("blur", function(){
              let min_price = $(this).attr("min")
              let max_price = $(this).attr("max")
              let current_price = $(this).val()
      
              //console.log("Current price is:", current_price);
              //console.log("Max price is:", max_price);
              //console.log("Min price is:", min_price);
      
              if(current_price < parseInt(min_price) || current_price > parseInt(max_price)){
                  console.log("Price error occured");
      
                  min_price = Math.round(min_price * 100) / 100
                  max_price = Math.round(max_price * 100) / 100
      
                  //console.log("Max price is:", max_price);
                  //console.log("Min price is:", min_price);
      
                  alert("Price must between ETB" +min_price + ' and ETB' +max_price)
                  $(this).val(min_price)
                  $('#range').val(min_price)
      
                  $(this).focus()
      
                  return false
              }
          })
        })
      </script> {% endcomment %}
    <script src="{% static 'asset/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'asset/vendor/sticky/sticky.js' %}"></script>
    <script src="{% static 'asset/vendor/jquery.plugin/jquery.plugin.min.js' %}"></script>
    <script src="{% static 'asset/vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'asset/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'asset/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'asset/vendor/zoom/jquery.zoom.js' %}"></script>
    <script src="{% static 'asset/vendor/photoswipe/photoswipe.js' %}"></script>
    <script src="{% static 'asset/vendor/photoswipe/photoswipe-ui-default.js' %}"></script>
    <script src="{% static 'asset/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'asset/vendor/jquery.countdown/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'asset/vendor/skrollr/skrollr.min.js' %}"></script>

    <!-- Main JS File -->
    <script src="{% static 'asset/js/main.min.js' %}"></script>
      <!-- FontAwesome CSS - loading as last, so it doesn't block rendering-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    </div>
  </body>
</html>

templates/scripts1.html
{% load static %}

    <script src="{% static 'asset/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'asset/vendor/jquery.plugin/jquery.plugin.min.js' %}"></script>
    <script src="{% static 'asset/vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'asset/vendor/zoom/jquery.zoom.js' %}"></script>
    <script src="{% static 'asset/vendor/jquery.countdown/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'asset/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'asset/vendor/skrollr/skrollr.min.js' %}"></script>

    <!-- Swiper JS -->
    <script src="{% static 'asset/vendor/swiper/swiper-bundle.min.js' %}"></script>

    <!-- Main JS -->
    <script src="{% static 'asset/js/main.min.js' %}"></script>